name: Infra Scan Re usable

on:
  workflow_dispatch:
  
jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: bkob:latest
          outputs: type=oci,dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bkob
          path: /tmp/image.tar
          
  twistlock-scan:
    needs: [build]
    
