name: Infra Scan

on:
  workflow_dispatch:
  
jobs:

  build-and-scan:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Build the image
        run: docker build -t bkob .
        
      - name: Twistlock Scan
        uses: actions/PISO-poc@v1
        with: |
          twistlock_url : ${{ PCC_CONSOLE_URL }}
          twistlock_username: ${{ secrets.PCC_USER }}
          twistlock_password : ${{ PCC_PASS }}
          image_name : bkob
