name: Infra Scan Re usable

on:
  workflow_dispatch:
  
jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Build and export
        run: |
          docker build -t bkob .
          docker save -o bkob.tar bkob
          
      - name: twistlock scan
        run: |
          curl -s -k -L -u ${{secrets.PCC_USER}}:${{secrets.PCC_PASS}} https://gps-twistlock.ift.pearsondev.tech/api/v1/util/twistcli > twistcli && chmod 0755 twistcli
          ./twistcli image scan -u ${{secrets.PCC_USER}} -p ${{secrets.PCC_PASS}} --address ${{secrets.PCC_CONSOLE_URL}} --details --output-file twistcli.log --ci bkob 
        
 #     - name: Upload artifact
 #       uses: actions/upload-artifact@v2
 #       with:
 #         name: bkob
 #         path: bkob.tar
          
#  twistlock-scan:
#    runs-on: ubuntu-latest
#    needs: build              
#    steps:
#      - name: Downloading image
#        uses: actions/download-artifact@v2
    
#      - name: Download twistlock cli
#        run: |
#          curl -s -k -L -u ${{secrets.PCC_USER}}:${{secrets.PCC_PASS}} https://gps-twistlock.ift.pearsondev.tech/api/v1/util/twistcli > twistcli && chmod 0755 twistcli
#          ./twistcli images scan -u ${{secrets.PCC_USER}} -p ${{secrets.PCC_PASS}} --address ${{secrets.PCC_CONSOLE_URL}} --details --output-file twistcli.log --ci bkob
