name: Infra Scan Re usable

on:
  workflow_dispatch:
  
jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      - name: Build and export
        run: |
          docker build -t bkob .
          docker save -o bkob.tar bkob
                
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bkob
          path: bkob.tar
                  
  twistlock-scan:
    runs-on: ubuntu-latest
    needs: build              
    steps:
      - name: Downloading image
        uses: actions/download-artifact@v3
        with: 
          name: bkob
          path: bkob.tar
          
      - name: checking files
        run: ls -la
      
      - name: Importing the Docker Image
        run: |
          docker load --input bkob | docker import bkob.tar bkob
          docker images
      
      - name: PISO Twistlock Scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
          pcc_user: ${{ secrets.PCC_USER }}
          pcc_pass: ${{ secrets.PCC_PASS }}
          image_name: bkob

#      - name: Download twistlock cli
#        run: |
#          curl -s -k -L -u ${{secrets.PCC_USER}}:${{secrets.PCC_PASS}} https://gps-twistlock.ift.pearsondev.tech/api/v1/util/twistcli > twistcli && chmod 0755 twistcli
#          ./twistcli images scan -u ${{secrets.PCC_USER}} -p ${{secrets.PCC_PASS}} --address ${{secrets.PCC_CONSOLE_URL}} --details --output-file twistcli.log --ci bkob
